-- ============================================================
-- Step 9: Grant Permissions
-- ============================================================
-- Run these grants to allow other roles to use the agent

-- Grant usage on databases and schemas
GRANT USAGE ON DATABASE PROD TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA PROD.RAW TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA PROD.FINAL TO ROLE PUBLIC;
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE PUBLIC;

-- Grant select on tables
GRANT SELECT ON ALL TABLES IN SCHEMA PROD.RAW TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD.FINAL TO ROLE PUBLIC;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA PROD.FINAL TO ROLE PUBLIC;

-- Grant usage on Cortex Search services
GRANT USAGE ON CORTEX SEARCH SERVICE PROD.FINAL.CONTRACT_SEARCH TO ROLE PUBLIC;

-- Grant usage on semantic view
GRANT SELECT ON SEMANTIC VIEW PROD.FINAL.CUSTOMER_360_SEMANTIC_VIEW TO ROLE PUBLIC;

-- Grant usage on agent
GRANT USAGE ON AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.CUSTOMER_360_AGENT TO ROLE PUBLIC;

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PUBLIC;

-- For specific roles (replace PUBLIC with actual role names as needed)
-- Example: GRANT USAGE ON AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.CUSTOMER_360_AGENT TO ROLE SALES_ANALYST;
