-- Step 5: Create Account-Level Sentiment Summary

CREATE OR REPLACE TABLE PROD.FINAL.ACCOUNT_CALL_SENTIMENT AS
SELECT
    ACCOUNT_NAME,
    COUNT(*) AS TOTAL_CALLS,
    SUM(CASE WHEN SENTIMENT_CATEGORY = 'positive' THEN 1 ELSE 0 END) AS POSITIVE_CALLS,
    SUM(CASE WHEN SENTIMENT_CATEGORY = 'negative' THEN 1 ELSE 0 END) AS NEGATIVE_CALLS,
    SUM(CASE WHEN SENTIMENT_CATEGORY = 'neutral' THEN 1 ELSE 0 END) AS NEUTRAL_CALLS,
    ROUND(SUM(CASE WHEN SENTIMENT_CATEGORY = 'positive' THEN 1 
                   WHEN SENTIMENT_CATEGORY = 'negative' THEN -1 
                   ELSE 0 END)::FLOAT / COUNT(*), 3) AS SENTIMENT_SCORE,
    MAX(CALL_DATE) AS LAST_CALL_DATE
FROM PROD.RAW.GONG_CALL_SENTIMENT
GROUP BY ACCOUNT_NAME;
