-- ============================================================
-- Step 2a: Create SFDC_ACCOUNT Table
-- ============================================================

CREATE OR REPLACE TABLE PROD.RAW.SFDC_ACCOUNT (
    ACCOUNT_ID VARCHAR(18) NOT NULL PRIMARY KEY,
    PARENT_ACCOUNT_ID VARCHAR(18),
    ACCOUNT_NAME VARCHAR(255),
    ACCOUNT_STATUS VARCHAR(255),
    ACCOUNT_TYPE VARCHAR(40),
    CREATED_DATE TIMESTAMP_NTZ(9),
    CUSTOMER_ACQUISITION_DATE DATE,
    RENEWAL_DATE DATE,
    CARR NUMBER(18,2),
    CARR_USD NUMBER(18,2),
    BILLING_STREET VARCHAR(255),
    BILLING_CITY VARCHAR(40),
    BILLING_STATE VARCHAR(80),
    BILLING_POSTALCODE VARCHAR(20),
    BILLING_COUNTRY VARCHAR(80),
    GEOGRAPHY VARCHAR(256),
    TERRITORY VARCHAR(256),
    TIMEZONE VARCHAR(256),
    INDUSTRY VARCHAR(40),
    SUB_INDUSTRY VARCHAR(255),
    PRIMARY_INDUSTRY VARCHAR(255),
    ANNUAL_REVENUE NUMBER(18,0),
    NUMBER_OF_EMPLOYEES NUMBER(38,0),
    WEBSITE VARCHAR(255),
    HEALTHSCORE VARCHAR(1500),
    TOP_ACCOUNT BOOLEAN,
    NAMED_ACCOUNT BOOLEAN,
    IS_CUSTOMER BOOLEAN,
    PAYING_CUSTOMER BOOLEAN
);
