-- ============================================================
-- Step 2b: Create SFDC_PRODUCT Table
-- ============================================================

CREATE OR REPLACE TABLE PROD.RAW.SFDC_PRODUCT (
    PRODUCT_ID VARCHAR(18) NOT NULL PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_CODE VARCHAR(255),
    PRODUCT_DESCRIPTION VARCHAR(4000),
    PRODUCT_FAMILY VARCHAR(40),
    PRODUCT_LINE VARCHAR(255),
    PRODUCT_CATEGORY VARCHAR(255),
    PRODUCT_UNIT VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    LIST_PRICE_USD NUMBER(14,2),
    CREATED_DATE TIMESTAMP_NTZ(9)
);
