-- ============================================================
-- Step 2c: Create SFDC_CONTRACT Table
-- ============================================================

CREATE OR REPLACE TABLE PROD.RAW.SFDC_CONTRACT (
    CONTRACT_ID VARCHAR(18) NOT NULL PRIMARY KEY,
    CONTRACT_NUMBER VARCHAR(30),
    ACCOUNT_ID VARCHAR(18),
    CURRENCY_ISO_CODE VARCHAR(3),
    START_DATE DATE,
    END_DATE DATE,
    CONTRACT_TERM NUMBER(38,0),
    CONTRACT_STATUS VARCHAR(40),
    BILLING_STREET VARCHAR(255),
    BILLING_CITY VARCHAR(40),
    BILLING_STATE VARCHAR(80),
    BILLING_POSTAL_CODE VARCHAR(20),
    BILLING_COUNTRY VARCHAR(80),
    TCV NUMBER(18,2),
    CARR NUMBER(18,2),
    MRR NUMBER(18,2),
    ARR NUMBER(18,2),
    CREATED_DATE TIMESTAMP_NTZ(9),
    ACTIVATED_DATE TIMESTAMP_NTZ(9),
    AUTO_RENEW BOOLEAN,
    CUSTOMER_SIGNED_DATE DATE,
    CUSTOMER_SIGNED_TITLE VARCHAR(40)
);
