-- ============================================================
-- Step 2d: Create SFDC_SUBSCRIPTION_CPQ Table
-- ============================================================

CREATE OR REPLACE TABLE PROD.RAW.SFDC_SUBSCRIPTION_CPQ (
    SUBSCRIPTION_ID VARCHAR(18) NOT NULL PRIMARY KEY,
    SUBSCRIPTION_NAME VARCHAR(80),
    ACCOUNT_ID VARCHAR(18),
    CONTRACT_ID VARCHAR(18),
    CONTRACT_NUMBER VARCHAR(255),
    PRODUCT_ID VARCHAR(18),
    PRODUCT_NAME VARCHAR(1300),
    CURRENCY_ISO_CODE VARCHAR(3),
    START_DATE DATE,
    END_DATE DATE,
    QUANTITY NUMBER(12,2),
    LIST_PRICE NUMBER(14,2),
    DISCOUNT NUMBER(11,2),
    CUSTOMER_PRICE NUMBER(14,2),
    NET_PRICE NUMBER(14,2),
    ARR NUMBER(18,2),
    MRR NUMBER(18,2),
    TCV NUMBER(18,2),
    CREATED_DATE TIMESTAMP_NTZ(9)
);
