-- ============================================================
-- Step 2f: Create GONG_TRANSCRIPT Table (NEW)
-- ============================================================
-- Stores call transcript metadata and content

CREATE OR REPLACE TABLE PROD.RAW.GONG_TRANSCRIPT (
    TRANSCRIPT_ID VARCHAR(18) NOT NULL PRIMARY KEY,
    ACCOUNT_ID VARCHAR(18),
    ACCOUNT_NAME VARCHAR(255),
    CALL_DATE DATE,
    CALL_DURATION_MINUTES NUMBER(10,2),
    PARTICIPANTS VARCHAR(1000),
    CALL_TYPE VARCHAR(50),
    SUMMARY VARCHAR(4000),
    KEY_INSIGHTS VARCHAR(4000),
    NEXT_STEPS VARCHAR(2000),
    SENTIMENT VARCHAR(50),
    TRANSCRIPT_TEXT VARCHAR(16777216),
    FILE_NAME VARCHAR(255),
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
