-- ============================================================
-- Step 7b: Create Gong Transcript Search Content
-- ============================================================
-- Prepares transcript data for Cortex Search

CREATE OR REPLACE TABLE PROD.FINAL.TRANSCRIPT_CONTENT (
    TRANSCRIPT_ID VARCHAR(18) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(18),
    ACCOUNT_NAME VARCHAR(255),
    CALL_DATE DATE,
    CALL_TYPE VARCHAR(50),
    PARTICIPANTS VARCHAR(1000),
    SUMMARY VARCHAR(4000),
    KEY_INSIGHTS VARCHAR(4000),
    SENTIMENT VARCHAR(50),
    FULL_CONTENT VARCHAR(16777216),
    FILE_NAME VARCHAR(255),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO PROD.FINAL.TRANSCRIPT_CONTENT
SELECT 
    TRANSCRIPT_ID,
    ACCOUNT_ID,
    ACCOUNT_NAME,
    CALL_DATE,
    CALL_TYPE,
    PARTICIPANTS,
    SUMMARY,
    KEY_INSIGHTS,
    SENTIMENT,
    -- Combine all fields for full-text search
    'GONG CALL TRANSCRIPT

Account: ' || ACCOUNT_NAME || '
Date: ' || CALL_DATE::VARCHAR || '
Type: ' || CALL_TYPE || '
Duration: ' || CALL_DURATION_MINUTES::VARCHAR || ' minutes
Participants: ' || PARTICIPANTS || '
Sentiment: ' || SENTIMENT || '

SUMMARY:
' || SUMMARY || '

KEY INSIGHTS:
' || KEY_INSIGHTS || '

NEXT STEPS:
' || NEXT_STEPS || '

FULL TRANSCRIPT:
' || TRANSCRIPT_TEXT AS full_content,
    FILE_NAME,
    CREATED_DATE
FROM PROD.RAW.GONG_TRANSCRIPT;

SELECT COUNT(*) FROM PROD.FINAL.TRANSCRIPT_CONTENT;
