-- Step 3: Create Cortex Search Service on Transcript Source Table

USE ROLE SYSADMIN;
USE WAREHOUSE DEFAULT_WH;

CREATE OR REPLACE CORTEX SEARCH SERVICE PROD.RAW.GONG_SEARCH_SERVICE
    ON CONTENT
    ATTRIBUTES FILE_NAME, ACCOUNT_NAME, CALL_DATE
    WAREHOUSE = DEFAULT_WH
    TARGET_LAG = '1 hour'
    AS (
        SELECT 
            FILE_NAME,
            ACCOUNT_NAME,
            CALL_DATE,
            CONTENT
        FROM PROD.RAW.GONG_TRANSCRIPT_SOURCE
    );
